apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-vw8p
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-vw8p
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-vw8p
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-vw8p
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-vw8p
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-kosw-tenant/rhtap-demo-app/hacbs-test-project-vw8p@sha256:67caf713446bfa09ad37e109d5b4cb938d9fe431719f8ea549df689a8c7a6ded
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
